const dessertsData = [
    { name: "Schokoladenmousse", chakra: "Herz", saison: "Winter", kalorien: 250 },
    { name: "Tiramisu", chakra: "Wurzel", saison: "Herbst", kalorien: 300 },
    { name: "Eiscreme", chakra: "Hals", saison: "Sommer", kalorien: 200 },
    { name: "Fruchtsalat", chakra: "Solarplexus", saison: "Sommer", kalorien: 180 },
    { name: "Apfelkuchen", chakra: "Herz", saison: "Herbst", kalorien: 350 },
    { name: "Mandelkekse", chakra: "Sakral", saison: "Frühling", kalorien: 220 },
    { name: "Zitronensorbet", chakra: "Hals", saison: "Sommer", kalorien: 120 },
    { name: "Brownies", chakra: "Wurzel", saison: "Winter", kalorien: 450 },
    { name: "Panna Cotta", chakra: "Herz", saison: "Frühling", kalorien: 340 },
    { name: "Mango-Pudding", chakra: "Solarplexus", saison: "Sommer", kalorien: 270 },
    { name: "Haselnusskuchen", chakra: "Drittes Auge", saison: "Winter", kalorien: 500 },
    { name: "Erdbeer-Quark", chakra: "Herz", saison: "Frühling", kalorien: 190 },
    { name: "Schwarzwälder Kirschtorte", chakra: "Wurzel", saison: "Herbst", kalorien: 520 },
    { name: "Honigwaffeln", chakra: "Solarplexus", saison: "Frühling", kalorien: 310 },
    { name: "Nougatpralinen", chakra: "Wurzel", saison: "Winter", kalorien: 380 },
    { name: "Bananenbrot", chakra: "Sakral", saison: "Herbst", kalorien: 260 },
    { name: "Vanillepudding", chakra: "Hals", saison: "Frühling", kalorien: 230 },
    { name: "Schokoladensoufflé", chakra: "Herz", saison: "Winter", kalorien: 490 },
    { name: "Dattelkonfekt", chakra: "Drittes Auge", saison: "Sommer", kalorien: 330 },
    { name: "Matcha-Kuchen", chakra: "Kronenchakra", saison: "Frühling", kalorien: 270 },
    { name: "Himbeer-Macarons", chakra: "Herz", saison: "Sommer", kalorien: 210 },
    { name: "Kokosnusskekse", chakra: "Solarplexus", saison: "Sommer", kalorien: 190 },
    { name: "Rote-Bete-Kuchen", chakra: "Wurzel", saison: "Herbst", kalorien: 240 },
    { name: "Mandel-Schokoriegel", chakra: "Sakral", saison: "Winter", kalorien: 370 },
    { name: "Sesam-Honig-Riegel", chakra: "Solarplexus", saison: "Sommer", kalorien: 280 },
    { name: "Erdnussbutter-Brownies", chakra: "Wurzel", saison: "Winter", kalorien: 490 },
    { name: "Pistazien-Kuchen", chakra: "Herz", saison: "Frühling", kalorien: 310 },
    { name: "Dunkle-Schokolade", chakra: "Drittes Auge", saison: "Jede", kalorien: 180 },
    { name: "Lavendel-Kekse", chakra: "Kronenchakra", saison: "Frühling", kalorien: 250 },
    { name: "Heidelbeer-Tarte", chakra: "Hals", saison: "Sommer", kalorien: 320 },
    { name: "Honig-Mandel-Kuchen", chakra: "Solarplexus", saison: "Herbst", kalorien: 280 },
    { name: "Gojibeeren-Pralinen", chakra: "Drittes Auge", saison: "Jede", kalorien: 210 },
    { name: "Feigen-Karamell-Dessert", chakra: "Wurzel", saison: "Herbst", kalorien: 400 },
    { name: "Chia-Pudding", chakra: "Kronenchakra", saison: "Jede", kalorien: 150 },
    { name: "Zimt-Quarkbällchen", chakra: "Sakral", saison: "Winter", kalorien: 300 },
    { name: "Ahornsirup-Walnuss-Kekse", chakra: "Herz", saison: "Herbst", kalorien: 290 },
    { name: "Joghurt-Honig-Becher", chakra: "Solarplexus", saison: "Sommer", kalorien: 200 },
    { name: "Orangencreme", chakra: "Hals", saison: "Winter", kalorien: 260 },
    { name: "Grüner-Tee-Mousse", chakra: "Kronenchakra", saison: "Frühling", kalorien: 190 },
    { name: "Marzipan-Riegel", chakra: "Sakral", saison: "Jede", kalorien: 350 },
    { name: "Mohnkuchen", chakra: "Drittes Auge", saison: "Winter", kalorien: 400 },
    { name: "Kardamom-Tarte", chakra: "Herz", saison: "Herbst", kalorien: 310 },
    { name: "Dattel-Walnuss-Konfekt", chakra: "Solarplexus", saison: "Winter", kalorien: 290 },
  ];
  
  export default dessertsData;
  